#ifndef VERSION_H__
#define VERSION_H__

#define LIBBLADERF_VERSION       "@VERSION@"

#define LIBBLADERF_VERSION_MAJOR 1
#define LIBBLADERF_VERSION_MINOR 5
#define LIBBLADERF_VERSION_PATCH 1

#endif
